feat: flow limits
axelarnetwork/axelar-cgp-sui pull request #66
Opened 2024-07-04 08:31 UTC by Foivos

2024-07-10 04:49 UTC, re1ro submitted a review, later dismissed

2024-07-19 05:19 UTC, re1ro requested changes
Needs to be rebased/merged and maybe split into smaller PRs

2024-07-31 07:30 UTC, milapsheth approved these changes

2024-07-31 07:30 UTC, milapsheth commented on move/abi/Move.toml
> +published-at = "0x4ee08bf35bdb2afbcc4f968a38dc2303106f3dfeedfe8c7919d47da7c90b8c4e"
revert adding this

2024-07-31 15:06 UTC, milapsheth approved these changes

2024-07-31 15:36 UTC, merged